name: Node.js CI

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Build vite
      run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      working-directory: client

    - name: Copy static files
      run: |
          cp -a client/dist/. dist/
          cp composer.json dist/
          
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
